# Generated by Django 4.2.7 on 2024-10-09 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
