# Generated by Django 4.2.7 on 2024-10-09 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='ismi',
            field=models.CharField(default=1, max_length=120),
            preserve_default=False,
        ),
    ]
