# Generated by Django 4.2.7 on 2024-10-09 14:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_author_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author_id',
        ),
    ]
