# Generated by Django 4.2.7 on 2024-10-12 13:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fani',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=100)),
                ('darsVaqti', models.TimeField()),
                ('juftmi', models.BooleanField(default=True)),
                ('kursNarxi', models.DecimalField(decimal_places=2, max_digits=7)),
            ],
        ),
        migrations.CreateModel(
            name='Oqituvchi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ismi', models.CharField(max_length=120)),
                ('familiyasi', models.CharField(max_length=120)),
                ('oquvchiSoni', models.IntegerField(default=0)),
                ('oyligi', models.DecimalField(decimal_places=3, max_digits=9)),
                ('foiz', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Xona',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomi', models.CharField(max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='Oquvchilar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ismi', models.CharField(max_length=120)),
                ('familiya', models.CharField(max_length=120)),
                ('parol', models.CharField(max_length=20)),
                ('tugSana', models.DateField()),
                ('fani', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='markaz.fani')),
            ],
        ),
        migrations.AddField(
            model_name='fani',
            name='oqituvchisi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='markaz.oqituvchi'),
        ),
        migrations.AddField(
            model_name='fani',
            name='xonasi',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='markaz.xona'),
        ),
    ]
