# Generated by Django 4.2.7 on 2024-10-12 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markaz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fani',
            name='kursNarxi',
            field=models.DecimalField(decimal_places=2, max_digits=9),
        ),
    ]
