# Generated by Django 4.2.7 on 2024-10-12 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markaz', '0002_alter_fani_kursnarxi'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fani',
            old_name='darsVaqti',
            new_name='darsBoshlanishVaqti',
        ),
        migrations.AddField(
            model_name='fani',
            name='davomEtadi',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
