# Generated by Django 4.2.7 on 2024-10-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markaz', '0003_rename_darsvaqti_fani_darsboshlanishvaqti_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='oqituvchi',
            name='foiz',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='oqituvchi',
            name='oyligi',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=9),
        ),
    ]
