# Generated by Django 4.2.7 on 2024-10-19 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markaz', '0004_alter_oqituvchi_foiz_alter_oqituvchi_oyligi'),
    ]

    operations = [
        migrations.AddField(
            model_name='xona',
            name='sigimi',
            field=models.IntegerField(default=1),
        ),
    ]
